# PostgreSQL Exporter for Database Monitoring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: video-streaming
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.12.0
        ports:
        - containerPort: 9187
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://video_user:video_pass@postgres-service:5432/video_monitoring_db?sslmode=disable"
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: "/etc/postgres_exporter/queries.yaml"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: postgres-queries
          mountPath: /etc/postgres_exporter
      volumes:
      - name: postgres-queries
        configMap:
          name: postgres-exporter-queries
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: video-streaming
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
---
# Custom queries for video streaming metrics
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-queries
  namespace: video-streaming
data:
  queries.yaml: |
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
      master: true
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size:
            usage: "GAUGE"
            description: "Disk space used by the database"
    
    # Video-specific metrics
    video_uploads:
      query: "SELECT COUNT(*) as total_videos, AVG(file_size) as avg_size FROM videos"
      master: true
      metrics:
        - total_videos:
            usage: "GAUGE"
            description: "Total number of uploaded videos"
        - avg_size:
            usage: "GAUGE"
            description: "Average video file size"
    
    # User activity metrics
    user_activity:
      query: "SELECT COUNT(DISTINCT user_id) as active_users FROM user_sessions WHERE created_at > NOW() - INTERVAL '1 hour'"
      master: true
      metrics:
        - active_users:
            usage: "GAUGE"
            description: "Active users in the last hour"
    
    # Video streaming metrics
    stream_performance:
      query: "SELECT COUNT(*) as total_streams, AVG(duration) as avg_duration FROM video_streams WHERE started_at > NOW() - INTERVAL '1 hour'"
      master: true
      metrics:
        - total_streams:
            usage: "GAUGE"
            description: "Total streams in the last hour"
        - avg_duration:
            usage: "GAUGE"
            description: "Average stream duration"
